# golangci.yml – GolangCI-Lint configuration

run:
  timeout: 5m
  skip-dirs:
      - fixtool
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - deadcode
    - structcheck
    - varcheck
    - goimports
    - gocritic
    - revive
    - asasalint
  disable:
    - scopelint
    - lll
    - funlen

linters-settings:
  goimports:
    local-prefixes: github.com/L1nch-lab/goesi
  revive:
    severity: warning
    rules:
      - name: indent-error-flow
        disabled: true
      - name: var-naming
        disabled: true
  gocritic:
    enabled-checks:
      - ifElseChain
      - rangeValCopy
      - typeSwitchVar

issues:
  exclude-use-default: false
  exclude:
    - "Error return value of .* is not checked"
    - "should not end with punctuation or newlines"
    - "field .* is unused"
