# golangci.yml – GolangCI-Lint configuration for L1nch-lab/goesi

run:
  timeout: 5m
  skip-dirs:
    - tools  # Skip internal developer tools
  tests: true

linters:
  enable:
    - errcheck           # Check that errors are not ignored
    - gosimple           # Simplify Go code
    - govet              # Go's vet tool
    - staticcheck        # Heuristic-based analyzer (very useful)
    - unused             # Detect unused variables/functions
    - ineffassign        # Detect ineffectual assignments
    - typecheck          # Detect type errors
    - deadcode           # Find unused code
    - structcheck        # Find unused struct fields
    - varcheck           # Find unused global variables and constants
    - goimports          # Checks import grouping and formatting
    - gocritic           # Collection of useful diagnostics
    - revive             # Fast, configurable, extensible linter
  disable:
    - scopelint          # Deprecated and merged into other linters
    - lll                # Line length – not critical here
    - funlen             # Method length – stylistic only

linters-settings:
  goimports:
    local-prefixes: github.com/L1nch-lab/goesi
  revive:
    severity: warning
    rules:
      - name: indent-error-flow
        disabled: true
      - name: var-naming
        disabled: true
  gocritic:
    enabled-checks:
      - ifElseChain
      - rangeValCopy
      - typeSwitchVar

issues:
  exclude-use-default: false
  exclude:
    - "Error return value of .* is not checked"       # Sometimes acceptable in tool code
    - "should not end with punctuation or newlines"   # Style rule – skip for now
    - "field .* is unused"                            # Can be intentional during refactoring
