# .github/workflows/gosec.yml
name: Gosec Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gosec:
    name: Run Gosec Security Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Gosec on production code
        run: |
          gosec -exclude-dir=tools ./...

        run: |
          gosec -fmt=sarif -out=gosec-report.sarif ./...
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
        sarif_file: gosec-report.sarif

