# .github/workflows/test.yml
name: Go Build & Test

on: [push, pull_request]

jobs:
  test:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Verify dependencies
        run: go mod tidy && git diff --exit-code go.sum go.mod

      - name: Build all packages
        run: go build -v ./...

      - name: Run all tests with verbose output
        run: go test -v ./...

      - name: Run race detector (optional but recommended)
        run: go test -race ./...
